#!/bin/bash

TARGET="$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)"
if [ -z "$TARGET" ]; then DIR="$(pwd)"
elif [ -d "$TARGET" ]; then DIR="$TARGET"
else DIR="$(dirname "$TARGET")"
fi

FILENAME="Презентация.pptx"
i=1
while [ -e "$DIR/$FILENAME" ]; do
  FILENAME="Презентация $i.pptx"
  ((i++))
done

cp ~/.local/share/file-templates/presentation_template.pptx "$DIR/$FILENAME"

